# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_auto_20171118_1433'),
    ]

    operations = [
        

        migrations.CreateModel(
            name='Messagelive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('aprrouve', models.BooleanField()),
                ('deja_envoye', models.BooleanField()),
            ],
        )
    ]
